#!/bin/sh
CHUKWA_CONF_DIR=/usr/local/chukwa/conf
CHUKWA_HOME=/usr/local/chukwa
CHUKWA_USER=chukwa

exec su ${CHUKWA_USER} -c "${CHUKWA_HOME}/bin/exec-data-loader.sh --config $CHUKWA_CONF_DIR HDFSUsage" &>/dev/null

