/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hadoop.chukwa.rest.objects;

// Generated May 28, 2009 3:39:53 PM by Hibernate Tools 3.2.4.GA
import java.sql.Timestamp;
/**
 * DfsFsnamesystem generated by hbm2java
 */
public class DfsFsNameSystem implements java.io.Serializable {
    static final long serialVersionUID = 1932906874487238992L;

    private Timestamp timestamp;
    private String host;
    private Double blocksTotal;
    private Double capacityRemainingGb;
    private Double capacityTotalGb;
    private Double capacityUsedGb;
    private Double filesTotal;
    private Double pendingReplicationBlocks;
    private Double scheduledReplicationBlocks;
    private Double totalLoad;
    private Double underReplicatedBlocks;

    public DfsFsNameSystem() {
    }

    public DfsFsNameSystem(Timestamp timestampe, String host,
			   Double blocksTotal, Double capacityRemainingGb,
			   Double capacityTotalGb, Double capacityUsedGb, Double filesTotal,
			   Double pendingReplicationBlocks, Double scheduledReplicationBlocks,
			   Double totalLoad, Double underReplicatedBlocks) {
	this.timestamp=timestamp;
	this.host=host;
	this.blocksTotal = blocksTotal;
	this.capacityRemainingGb = capacityRemainingGb;
	this.capacityTotalGb = capacityTotalGb;
	this.capacityUsedGb = capacityUsedGb;
	this.filesTotal = filesTotal;
	this.pendingReplicationBlocks = pendingReplicationBlocks;
	this.scheduledReplicationBlocks = scheduledReplicationBlocks;
	this.totalLoad = totalLoad;
	this.underReplicatedBlocks = underReplicatedBlocks;
    }

    public Timestamp getTimestamp() {
	return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
	this.timestamp = timestamp;
    }

    public String getHost() {
	return this.host;
    }

    public void setHost(String host) {
	this.host=host;
    }

    public Double getBlocksTotal() {
	return this.blocksTotal;
    }

    public void setBlocksTotal(Double blocksTotal) {
	this.blocksTotal = blocksTotal;
    }

    public Double getCapacityRemainingGb() {
	return this.capacityRemainingGb;
    }

    public void setCapacityRemainingGb(Double capacityRemainingGb) {
	this.capacityRemainingGb = capacityRemainingGb;
    }

    public Double getCapacityTotalGb() {
	return this.capacityTotalGb;
    }

    public void setCapacityTotalGb(Double capacityTotalGb) {
	this.capacityTotalGb = capacityTotalGb;
    }

    public Double getCapacityUsedGb() {
	return this.capacityUsedGb;
    }

    public void setCapacityUsedGb(Double capacityUsedGb) {
	this.capacityUsedGb = capacityUsedGb;
    }

    public Double getFilesTotal() {
	return this.filesTotal;
    }

    public void setFilesTotal(Double filesTotal) {
	this.filesTotal = filesTotal;
    }

    public Double getPendingReplicationBlocks() {
	return this.pendingReplicationBlocks;
    }

    public void setPendingReplicationBlocks(Double pendingReplicationBlocks) {
	this.pendingReplicationBlocks = pendingReplicationBlocks;
    }

    public Double getScheduledReplicationBlocks() {
	return this.scheduledReplicationBlocks;
    }

    public void setScheduledReplicationBlocks(Double scheduledReplicationBlocks) {
	this.scheduledReplicationBlocks = scheduledReplicationBlocks;
    }

    public Double getTotalLoad() {
	return this.totalLoad;
    }

    public void setTotalLoad(Double totalLoad) {
	this.totalLoad = totalLoad;
    }

    public Double getUnderReplicatedBlocks() {
	return this.underReplicatedBlocks;
    }

    public void setUnderReplicatedBlocks(Double underReplicatedBlocks) {
	this.underReplicatedBlocks = underReplicatedBlocks;
    }

}
