/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hadoop.chukwa.rest.objects;

// Generated May 28, 2009 3:39:53 PM by Hibernate Tools 3.2.4.GA
import java.sql.Timestamp;

/**
 * Disk generated by hbm2java
 */
public class Disk implements java.io.Serializable {
    static final long serialVersionUID = -394214660094738201L;

    private Timestamp timestamp;
    private String host;
    private String mount;
    private Double used;
    private Double available;
    private Double usedPercent;
    private String fs;

    public Disk() {
    }

    public Disk(Timestamp timestamp, String host, String mount, Double used, Double available,
		Double usedPercent, String fs) {
	this.timestamp = timestamp;
	this.host = host;
	this.mount = this.mount;
	this.used = used;
	this.available = available;
	this.usedPercent = usedPercent;
	this.fs = fs;
    }

    public Timestamp getTimestamp() {
	return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
	this.timestamp = timestamp;
    }

    public String getHost() {
	return this.host;
    }

    public void setHost(String host) {
	this.host=host;
    }

    public String getMount() {
	return this.mount;
    }

    public void setMount(String mount) {
	this.mount=mount;
    }

    public Double getUsed() {
	return this.used;
    }

    public void setUsed(Double used) {
	this.used = used;
    }

    public Double getAvailable() {
	return this.available;
    }

    public void setAvailable(Double available) {
	this.available = available;
    }

    public Double getUsedPercent() {
	return this.usedPercent;
    }

    public void setUsedPercent(Double usedPercent) {
	this.usedPercent = usedPercent;
    }

    public String getFs() {
	return this.fs;
    }

    public void setFs(String fs) {
	this.fs = fs;
    }

}
